### ISSUE TITLE
Create splash screen with animations

### ISSUE THREAD

**Issue by ghost** [Gindiascholars2k18/GIS-Android-Application#3]
we need someone to design splash screen for our GIS application, use the below image as a reference and create it, also animate it
There is more to come in future.

![splash_scr_mock](https://user-images.githubusercontent.com/42109980/53110197-79e9aa80-3560-11e9-9df2-959905ffda6f.jpg)

**Comment by sdzshn3** [comment]
Need materials like logo or gif.

**Comment by Kvaibhav01** [comment]
@sdzshn3, the logo is [still in development](https://googleindiascholars2k.slack.com/archives/GFSS308BE/p1550436876000100).

**Comment by ghost** [comment]
Look at another issue Vaibhav gave mockup in his reply

**Comment by sdzshn3** [comment]
How exactly do you want splash screen?
Only at first time app launched or everytime we launch app?
Do you want the splash screen delay to start activity or should i place splash screen in the white screen which we see immediately after launching an app?

Incase of showing splash screen without delay, then we need to have an image of splash screen and set it as theme for splashScreen activity in manifests. Incase if we select this, animation is not possible.
If you want animation, then we need to delay.

**Comment by Kvaibhav01** [comment]
I think the splash screen should come every time we launch the app, it will just have a gradient and the logo which will animate. You can do slide in/out or fade in/out animations, just don't make it long, keep it under 4 seconds. You can also add a loading indicator below the logo.

Yes, add a delay, we want the animation. @iamhshaikh @sdzshn3

**Comment by ghost** [comment]
@Kvaibhav01 is right
