### ISSUE TITLE
Create navigation drawer as per mock-up

### ISSUE THREAD

**Issue by ghost** [Gindiascholars2k18/GIS-Android-Application#6]
**create navigation drawer as per mock-up given below**

![nav_drawer_mock](https://user-images.githubusercontent.com/42109980/53281442-829fd380-374e-11e9-80dd-d94cbdcb986e.jpg)

**Comment by sdzshn3** [comment]
Assign it to me.

**Comment by sdzshn3** [comment]
Added in PR #7
